-- 테이블
-- 유저 테이블 생성
CREATE TABLE USERS(
    ID VARCHAR2(30) NOT NULL PRIMARY KEY,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- 상품 테이블 생성
CREATE TABLE GOODS(
    G_NO NUMBER NOT NULL PRIMARY KEY,
    G_IMAGE VARCHAR2(100)NOT NULL,
    G_NAME VARCHAR2(300) NOT NULL,
    G_PRICE NUMBER NOT NULL
);

-- 구매 상품 테이블 생성
CREATE TABLE BASKET(
    B_NO NUMBER NOT NULL PRIMARY KEY,
    B_IMAGE VARCHAR2(100)NOT NULL,
    B_NAME VARCHAR2(300) NOT NULL,
    B_PRICE NUMBER NOT NULL,
    B_PURCHASE_CNT NUMBER NOT NULL,
    B_PURCHASE_PRICE NUMBER NOT NULL,
    G_NO NUMBER NOT NULL REFERENCES GOODS(G_NO),
    ID VARCHAR2(30) NOT NULL REFERENCES USERS(ID)
);

-- 시퀀스
-- 상품 시퀀스
CREATE SEQUENCE SEQ_GOODS
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE;

-- 구매 상품 시퀀스
CREATE SEQUENCE SEQ_BASKET
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE;

DROP SEQUENCE SEQ_BASKET;
DROP SEQUENCE SEQ_GOODS;

DROP TABLE BASKET;
DROP TABLE GOODS;
DROP TABLE USERS;

INSERT INTO users (id, pw, name, birth, tel, reg_date)
VALUES ('green', '1234', '김그린', '20040101', '01012345678', SYSDATE);

INSERT INTO basket (b_no, b_image, b_name, b_price, b_purchase_cnt, b_purchase_price, g_no, id)
SELECT seq_basket.nextval, '/img/productimg1.png', '[동원]보성홍차 아이스티', 2000, 1, 2000, 1, 'green'
FROM goods G
WHERE G.g_no = 1;

SELECT SUM(b_purchase_price)
FROM basket
WHERE id = 'green';








