-- 테이블
-- 유저 테이블 생성
CREATE TABLE USERS(
    USER_NO NUMBER NOT NULL PRIMARY KEY,
    ID VARCHAR2(30) NOT NULL,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- 상품 테이블 생성
CREATE TABLE GOODS(
    G_NO NUMBER NOT NULL PRIMARY KEY,
    G_NAME VARCHAR2(300) NOT NULL,
    G_PRICE NUMBER NOT NULL,
    G_STOCK NUMBER NOT NULL,
    G_AGE_RES VARCHAR2(20) NOT NULL
);

-- 구매 상품 테이블 생성
CREATE TABLE BASKET(
    B_NO NUMBER NOT NULL PRIMARY KEY,
    B_NAME VARCHAR2(300) NOT NULL,
    B_PRICE NUMBER NOT NULL,
    B_PURCHASE_CNT NUMBER NOT NULL,
    B_PURCHASE_PRICE NUMBER NOT NULL,
    B_TOTAL_CNT NUMBER NOT NULL,
    B_TOTAL_PRICE NUMBER NOT NULL,
    G_NO NUMBER NOT NULL REFERENCES GOODS(G_NO),
    USERNO NUMBER NOT NULL REFERENCES USERS(USER_NO)
);

-- 시퀀스
-- 유저 시퀀스
CREATE SEQUENCE SEQ_USERS
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE;

-- 상품 시퀀스
CREATE SEQUENCE SEQ_GOODS
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE;

-- 구매 상품 시퀀스
CREATE SEQUENCE SEQ_BASKET
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE;

DROP SEQUENCE SEQ_BASKET;
DROP SEQUENCE SEQ_GOODS;
DROP SEQUENCE SEQ_USERS;

DROP TABLE BASKET;
DROP TABLE GOODS;
DROP TABLE USERS;

















